/**
 * MI PROFE
 * The MI PROFE-API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerRespondeDto { 
    id: number;
    status: boolean;
    firstName: string;
    lastName: string;
    idDocument: string;
    gender: string;
    phone?: string;
}

