/**
 * Laboratory
 * The Laboratory-API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginUserResponseDto { 
    email: string;
    id: number;
    lastName: string;
    firstName: string;
    idDocument: string;
    role: string;
    loginStamp: number;
    patient: object;
}

