/**
 * Laboratory
 * The Laboratory-API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateStudyExamDto } from './create-study-exam-dto';


export interface StudyRespondeDto { 
    id: number;
    stage: string;
    date: string;
    note?: string;
    sendEmail: boolean;
    total: number;
    patient: object;
    studyExams: Array<CreateStudyExamDto>;
}

