/**
 * Laboratory
 * The Laboratory-API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdCreateEntity } from './id-create-entity';
import { CreateStudyExamDto } from './create-study-exam-dto';


export interface UpdateStudyDto { 
    stage?: string;
    date?: string;
    note?: string;
    sendEmail?: boolean;
    total?: number;
    patient?: IdCreateEntity;
    studyExams?: Array<CreateStudyExamDto>;
}

