export * from './auth.service';
import { AuthService } from './auth.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './sale.service';
import { SaleService } from './sale.service';
export * from './statistics.service';
import { StatisticsService } from './statistics.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AuthService, CategoriesService, CustomersService, DefaultService, OrdersService, ProductsService, SaleService, StatisticsService, UsersService];
